### ISSUE TITLE
The module cannot be installed

### ISSUE THREAD

**Issue by Vesselchuck** [xaukael/card-tokens#1]
![image](https://user-images.githubusercontent.com/70449411/218034995-da6d1d66-25dd-46f2-bbdb-667e4e445df2.png)

**Comment by dutchcolonial** [comment]
I can confirm the same issue.

**Comment by xaukael** [comment]
Typo in the manifest. Can you try again and let me know if it works now. I might need to iterate the version for the package manager to notice the updated json.

**Comment by dutchcolonial** [comment]
Issue has been fixed with latest update

**Comment by dutchcolonial** [comment]
Hi there. Yes, it works now. I added a comment in Github.
I just refreshed my browser window and that was enough for me to be able to
install it (before a refresh it still gave an error)
