### ISSUE TITLE
Request for Integration with Orcnog Card Viewer Module

### ISSUE THREAD

**Issue by brunocalado** [xaukael/card-tokens#14]
**Issue Description:**
I'm a huge fan of your module, and I truly appreciate the effort you've put into its development. I have a feature request that I believe would greatly enhance its functionality and user experience. I would love to see an integration between your module and the Orcnog Card Viewer module.

https://github.com/xaukael/card-tokens/assets/4999783/a92278b1-424d-4b0c-9088-fe91503f9019

It's very easy to use Orcnog Card Viewer Module. You module just have to call this code if Orcnog is activated. This would allow the card to show up in this amazing 3D view at the same time the card appears on the canvas.
```js
// Draws, views, and discards a card from a given deck name. Leave discardPile null to smart-match an existing discard pile name or auto-create a new one named "[your deck name] - Discard Pile".

let deckName = 'Persegue2';
let discardPile = 'Descarte';
let share = true;

OrcnogFancyCardDealer({
   deckName: deckName ,
   discardPileName: discardPile
}).draw(share);
```

Thank you.

**Keep up the excellent work!**

**Comment by xaukael** [comment]
cool visuals, but their implementation is narrow and the functions that are exposed not really conducive to integration

**Comment by xaukael** [comment]
You can make drawings and then deal to the drawings and utilize that module's display on deal functionality.

**Comment by brunocalado** [comment]
> 

Thank you!
