### ISSUE TITLE
The aspect ratio of the card is not respected when placed on the canvas.

### ISSUE THREAD

**Issue by GabrielOsvair** [xaukael/card-tokens#15]
It would be nice if the 2:3 aspect ratio was respected, so on a 50ppi grid the size looks good.

![image](https://github.com/xaukael/card-tokens/assets/67530921/c2df14b2-cddc-49fd-bd5d-d0219717905b)
![image](https://github.com/xaukael/card-tokens/assets/67530921/b5b7f532-e22a-4950-856b-913754132550)
![image](https://github.com/xaukael/card-tokens/assets/67530921/7616e9c3-84e1-4135-af3c-b1e1128fa4b4)

**Comment by xaukael** [comment]
It should do as in the second image. Maybe system or module interference. Have you tried with no other modules? What system are you using?

 ```
token: {
      texture: {src:card.face!=null?card.faces[card.face].img:card.faces[0].img}, 
      height: card.height || game.settings.get("card-tokens", "height"), 
      width: card.width || game.settings.get("card-tokens", "width"),
      texture:{rotation: card.rotation},
      displayName: game.settings.get("card-tokens", "displayName"),
      displayBars: CONST.TOKEN_DISPLAY_MODES.NONE,
      bar1: {attribute: null},
      bar2: {attribute: null}
    },
```

**Comment by GabrielOsvair** [comment]
Foundry v10 (latest), D&D 5e v2.2.2, just it and the dependencies, and the same thing happens. I'll try to reinstall, and a new world.

**Comment by GabrielOsvair** [comment]
Works on the Crucible system

**Comment by xaukael** [comment]
I'd bet dnd5e is setting token dimensions based on the size of the actor. I will ask around to see if there is a way around that.

**Comment by xaukael** [comment]
I put a temporary fix for dnd5e in 0.5.2

**Comment by GabrielOsvair** [comment]
I tested it and it still doesn't respect the aspect ratio...

**Comment by xaukael** [comment]
I tested and it is working on v10 and v11. I pushed another version just in case the other one did not take for some reason. I had some syntax cleanup to do anyhow.

**Comment by GabrielOsvair** [comment]
Now with D&D in v2.3 it works
