### ISSUE TITLE
Error Occurs When Moving a Card on Canvas

### ISSUE THREAD

**Issue by brunocalado** [xaukael/card-tokens#5]
**Description**
When attempting to move a card that is placed on the canvas using the Card Tokens module, an error is generated. The error details can be found in the attached image.

**Steps to Reproduce**
- Open the Foundry VTT with the Card Tokens module installed.
- Place a card on the canvas.
- Attempt to move the card to a different location on the canvas.
- Observe the error that is generated.

**Environment:**
Foundry VTT Version: 11
Card Tokens Module Version: 0.4.6
Operating System: Win10
Browser: Chrome
SWADE

![image](https://github.com/xaukael/card-tokens/assets/4999783/516b2821-bfd4-49f2-bdfa-66b3d1e5e384)

**Comment by xaukael** [comment]
This does not happen for me on 0.4.7. Update to 0.4.7 to fix the base actor issue. Reset the decks. Try again.

**Comment by brunocalado** [comment]
> This does not happen for me on 0.4.7. Update to 0.4.7 to fix the base actor issue. Reset the decks. Try again.

I reset the deck. I dragged a card and got this warning:
![image](https://github.com/xaukael/card-tokens/assets/4999783/7f0d5766-4362-4e6e-a71b-4c7b309c8123)
commons.js:2004 Error: You are accessing the TokenDocument#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1993:19)
    at TokenDocument._logV10CompatibilityWarning (commons.js:8435:14)
    at get data [as data] (commons.js:8323:24)
    at Object.fn (card-tokens.js:63:11)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preCreateDocumentArray (foundry.js:13476:44)
    at async ClientDatabaseBackend._createDocuments (foundry.js:13362:22)

**Comment by xaukael** [comment]
good to know, not a pressing or breaking issue, but I will have it fixed in the next version regardless.
