### ISSUE TITLE
Bug Report - Inconsistent Card Reset Behavior between Player and GM

### ISSUE THREAD

**Issue by brunocalado** [xaukael/card-tokens#8]
Description:
I encountered an issue related to card resets when using the Card Tokens module. Here's the scenario:

1. As the GM, I created a hand for Player 1 and a discard pile.
2. I logged in to a different browser as Player 1 and placed several cards on the canvas.
3. While still logged in as Player 1, I clicked the "Reset Hand" button, expecting all cards to be returned to the hand. However, only some of the cards were returned.
4. Switching to the GM browser, I tried resetting the deck, but the cards placed on the canvas by Player 1 were not removed.
![image](https://github.com/xaukael/card-tokens/assets/4999783/3ffa0a6b-e5de-436b-9a22-b6c80f2a077d)

This inconsistent behavior between the player and GM browsers makes it challenging to properly manage the cards on the canvas. It seems that the card reset function does not fully synchronize between different user sessions.

I kindly request a review and resolution of this issue to ensure consistent card reset functionality across all user sessions. Thank you for your attention to this matter.

**Comment by xaukael** [comment]
fixed in 0.4.8
