### ISSUE TITLE
Request for License Specification in the Card Tokens Repository

### ISSUE THREAD

**Issue by brunocalado** [xaukael/card-tokens#9]
Description:
I noticed that the Card Tokens repository does not have a defined license. Having a clear license is important for establishing the permissions and restrictions for using and distributing the code. 

I kindly request the addition of a specific license to the repository, such as the MIT or GNU license. This will provide clarity for users and contributors regarding the terms under which they can use, modify, and distribute the Card Tokens module.

Thank you for considering this request, and I appreciate your attention to this matter.

**Comment by xaukael** [comment]
done
